[build]
  # Command to install dependencies
  command = "npm install"

[start]
  # Command to start your app
  command = "node server.js"
  
[[services]]
  # Name of the service (can be any name)
  name = "backend"
 
